name: Build and Deploy to Stage Server

# on:
#   pull_request:
#     branches:
#       - develop
#     types: [closed]
#   workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ${{ env.REGISTRY }}/${{ vars.REP_OWNER }}/${{ vars.IMAGE_NAME }}

defaults:
  run:
    working-directory: .

jobs:
  build_and_push_images:
    name: Build and Push Images to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push news scraper backend image
        if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./deploy/webcat/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PATH }}:stage
            ${{ env.IMAGE_PATH }}:latest
            ${{ env.IMAGE_PATH }}:${{ github.sha }}
          cache-from: |
            type=registry,ref=${{ env.IMAGE_PATH }}:buildcache
            type=local,src=/tmp/.buildx-cache
          cache-to: |
            type=registry,ref=${{ env.IMAGE_PATH }}:buildcache,mode=max
            type=local,dest=/tmp/.buildx-cache
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.repository.updated_at }}

  deploy:
    name: Deploy and Start the Application
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build_and_push_images

    steps:
      - name: Check out the deployment repository
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REP_OWNER }}/${{ vars.REPO }}
          token: ${{ secrets.REGISTRY_PAT }}

      - name: Copy Docker Compose and config files to stage server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.STAGE_HOST }}
          username: ${{ secrets.STAGE_SSH_USERNAME }}
          key: ${{ secrets.STAGE_SSH_KEY }}
          port: ${{ secrets.STAGE_SSH_PORT }}
          source: "docker-compose.stage.yaml,deploy"
          target: ${{ vars.DEPLOY_PATH }}
          overwrite: true

      - name: Deploy and start application on stage server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGE_HOST }}
          username: ${{ secrets.STAGE_SSH_USERNAME }}
          key: ${{ secrets.STAGE_SSH_KEY }}
          port: ${{ secrets.STAGE_SSH_PORT }}
          script: |
            mkdir -p ${{ vars.DEPLOY_PATH }} && cd ${{ vars.DEPLOY_PATH }}

            echo "${{ secrets.REGISTRY_PAT }}" | docker login ${{ env.REGISTRY }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

            docker image prune -f
            docker compose -f docker-compose.stage.yaml down --remove-orphans
            docker compose -f docker-compose.stage.yaml pull
            docker compose -f docker-compose.stage.yaml up -d --remove-orphans
